apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: letsencrypt-staging
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
    - hosts:
      - grafana.104.155.172.128.xip.io
      secretName: grafana-cicd-auzmor-tls
  rules:
    - host: grafana.104.155.172.128.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
