apiVersion: v1
kind: Secret
metadata:
  name: {{ template "percona.fullname" . }}-secrets
  labels:
    app: {{ template "percona.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.passwords.mysqlroot }}
  root:  {{ .Values.passwords.mysqlroot| b64enc | quote }}
  {{ else }}
  root: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.passwords.xtrabackup }}
  xtrabackup:  {{ .Values.passwords.xtrabackup| b64enc | quote }}
  {{ else }}
  xtrabackup: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.passwords.monitor }}
  monitor:  {{ .Values.passwords.monitor| b64enc | quote }}
  {{ else }}
  monitor: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.passwords.clustercheck }}
  clustercheck:  {{ .Values.passwords.clustercheck| b64enc | quote }}
  {{ else }}
  clustercheck: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.passwords.proxyuser }}
  proxyuser:  {{ .Values.passwords.proxyuser| b64enc | quote }}
  {{ else }}
  proxyuser: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
