name: pxc
version: 1.0.0
description: free, fully compatible, enhanced, open source drop-in replacement for
  MySQL
keywords:
- mysql
- percona
- database
- sql
home: https://www.percona.com/
icon: https://www.percona.com/sites/all/themes/percona2015/logo.png
sources:
- https://github.com/kubernetes/charts
- https://github.com/docker-library/percona
maintainers:
- name: Percona Engineering Team
  email: info@percona.com
engine: gotpl
